### ISSUE TITLE
Show scoreboard stats on profile

### ISSUE THREAD

**Issue by TheSweMaster** [Yakimych/result-log#30]
Would be nice to see all the same weekly scoreboard stats on the player profile but for all time instead of just weekly. Because I love statistics <3

**Comment by Yakimych** [comment]
Just so that I understand this correctly - we want the data in this table, but aggregated for all results in the system (not just per week)?

![image](https://user-images.githubusercontent.com/5010901/63641125-939fb200-c6a9-11e9-9c08-7ba63df9425a.png)

**Comment by TheSweMaster** [comment]
Correct.

**Comment by Yakimych** [comment]
Ok, here is what I did: instead of adding this to the player profile page, I've extended the "history" page with to/from dates, as well as an "All time" button. This allows to view stats for any custom period of time (including "All time"):

![image](https://user-images.githubusercontent.com/5010901/63647022-caaeab80-c71b-11e9-8327-a501fa853168.png)

**Comment by Yakimych** [comment]
Throwing in the same stats on the Player profile too:

![image](https://user-images.githubusercontent.com/5010901/63648552-ad84d780-c731-11e9-8605-1d40af494ba9.png)
